### ISSUE TITLE
UNI Dialer literally Unuseable

### ISSUE THREAD

**Issue by MR-Spagetty** [MineDragonCZ/Aunis1#51]
after the update that causes the uni dialer to "crack" the UNI dialer is completely unusable due to the fact that as soon as you go to use it, it cracks

**Comment by MR-Spagetty** [comment]
ok just discovered that the Dialer only seems to crack in the overworld

**Comment by MR-Spagetty** [comment]
also when a dialer cracks it loses ALL data on it for example the addresses stored on the dialer

**Comment by matousss** [comment]
It is not issue, it prevent minecraft from crash (uni dialer crash bug). Sometimes got nbt corrupted and cause crash that is why it lose all data.

**Comment by oddrobbia** [comment]
here is the log i got crashed from the dialer even the event happened from prevent from crashing https://paste.ee/p/uhtcw

**Comment by Fredyman95** [comment]
Crash report from server - Ender pearl hit shield/iris - server crashed (reported by MR-Spagetty)

Time: 11/16/21 9:10 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
	at mrjake.aunis.stargate.teleportation.EventHorizon.teleportEntity(EventHorizon.java:137)
	at mrjake.aunis.stargate.teleportation.EventHorizon.scheduleTeleportation(EventHorizon.java:114)
	at mrjake.aunis.tileentity.stargate.StargateAbstractBaseTile.func_73660_a(StargateAbstractBaseTile.java:735)
	at mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.func_73660_a(StargateClassicBaseTile.java:235)
	at mrjake.aunis.tileentity.stargate.StargatePegasusBaseTile.func_73660_a(StargatePegasusBaseTile.java:386)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by matousss** [comment]
the last 2 logs are not crash reports and problem is with jei not with aunis
