### ISSUE TITLE
enderpearl iris crash

### ISSUE THREAD

**Issue by MR-Spagetty** [MineDragonCZ/Aunis1#52]
when an ender pearl hits an iris(through a wormhole) it causes servers to crash

**Comment by matousss** [comment]
I was unable to reproduce the bug, plese provide log.

**Comment by MR-Spagetty** [comment]
On the Aunis craft server i dialed the magori team gage then through an enderpearl through which caused the server to crash

**Comment by matousss** [comment]
Crash report from server - Ender pearl hit shield/iris - server crashed (reported by MR-Spagetty)

Time: 11/16/21 9:10 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
at mrjake.aunis.stargate.teleportation.EventHorizon.teleportEntity(EventHorizon.java:137)
at mrjake.aunis.stargate.teleportation.EventHorizon.scheduleTeleportation(EventHorizon.java:114)
at mrjake.aunis.tileentity.stargate.StargateAbstractBaseTile.func_73660_a(StargateAbstractBaseTile.java:735)
at mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.func_73660_a(StargateClassicBaseTile.java:235)
at mrjake.aunis.tileentity.stargate.StargatePegasusBaseTile.func_73660_a(StargatePegasusBaseTile.java:386)
at net.minecraft.world.World.func_72939_s(World.java:1838)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)
